language: cpp
compiler: gcc
sudo: require
dist: xenial # due to libqtermwidget5-0-dev missing in trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base libgl1-mesa-dev libqtermwidget5-0-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  # libcprime, a dependency
  - git clone https://github.com/rahmanshaber/libcprime
  - cd libcprime
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - sudo make -j$(nproc) install 
  - cd ..
  # The application itself
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - mkdir -p appdir/usr/share/icons/scalable/apps/ ; cp appdir/usr/share/coreapps/icons/coreterminal.svg appdir/usr/share/icons/scalable/apps/
  - sed -i -e 's|^Icon=.*|Icon=coreterminal|g' appdir/usr/share/applications/coreterminal.desktop
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Core*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
